---
- name: Configure Tomcat server
  template: src=server.xml dest=/var/lib/tomcat8/conf/
  notify: restart tomcat8

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat8 mode=0755

- name: Start Tomcat
  shell: service tomcat8 restart

- name: wait for tomcat to start
  wait_for: port={{ http_port }}
